# Generated by Django 3.2.7 on 2021-11-07 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('size', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=200)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('attempts', models.IntegerField(default=1)),
                ('end_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DownloadOngoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('size', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=200)),
                ('speed', models.IntegerField(null=True)),
                ('received_bytes', models.IntegerField(null=True)),
                ('progress', models.IntegerField(null=True)),
                ('eta', models.DateTimeField(null=True)),
                ('time_left', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('canceled', models.BooleanField(default=False)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('server', models.CharField(max_length=200)),
                ('channel', models.CharField(max_length=200)),
                ('bot', models.CharField(max_length=200)),
                ('package_number', models.IntegerField(null=True)),
                ('attempts', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DownloadQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('size', models.IntegerField(null=True)),
                ('server', models.CharField(max_length=200)),
                ('channel', models.CharField(max_length=200)),
                ('bot', models.CharField(max_length=200)),
                ('package_number', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadOngoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('size', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=200)),
                ('speed', models.IntegerField(null=True)),
                ('progress', models.IntegerField(null=True)),
                ('completed', models.IntegerField(null=True)),
                ('eta', models.DateTimeField(null=True)),
                ('time_left', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('server', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpnpPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DownloadSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_box_state', models.BooleanField(default=True)),
                ('shutdown', models.BooleanField(default=False)),
                ('queue_similar', models.BooleanField(default=True)),
                ('restart', models.BooleanField(default=False)),
                ('path', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('bluray', 'Maximum (BluRay)'), ('1080', 'Excellent (1080p)'), ('720', 'Good (720p)'), ('hd', 'Normal')], default='720', max_length=6)),
                ('contains', models.ManyToManyField(related_name='contained', to='core.SearchTerm')),
                ('excludes', models.ManyToManyField(related_name='excluded', to='core.SearchTerm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
